Traceback (most recent call last):
  File "/mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/finetune_kfold_pearl.py", line 111, in <module>
    main()
    ~~~~^^
  File "/mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/finetune_kfold_pearl.py", line 83, in main
    data_loader = load_dataset.get_data_loader()
  File "/mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/datasets/pearl_kfold_dataset.py", line 47, in get_data_loader
    train_set = CustomDataset(self.datasets_dir, mode='train')
  File "/mnt/disk1/aiotlab/namth/EEGFoundationModel/CBraMod/datasets/pearl_kfold_dataset.py", line 17, in __init__
    self.db = lmdb.open(data_dir, readonly=True, lock=False, readahead=True, meminit=False)
              ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lmdb.Error: mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/pearl_30s/fold_0: No such file or directory
